### ISSUE TITLE
Cloud Vision API 공부하기

### ISSUE THREAD

**Issue by loocia1910** [codestates/Mission-Eco#106]
### ISSUE
- Group: client, server

### TODO
- [x] 어떤 기능이 구현 될 수 있는지 검색
- [x] 실제 구현 튜토리얼 영상이 있는지 검색
- [x] 코드 구현 방법 검색
