### ISSUE TITLE
[ERROR] 리액트 메모리 누수 에러 

### ISSUE THREAD

**Issue by HYO00** [codestates/Mission-Eco#117]
### ISSUE
- Group: client
- Type: bug
- Detail: Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

### TODO
- [ ] Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
- [ ] 뭘까...? 메모리 ㄴ수ㅜ...?
- [ ] index.js:1 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at Navbar (https://localhost:3000/static/js/main.chunk.js:3700:83)
    at div
    at Main (https://localhost:3000/static/js/main.chunk.js:4890:83)

### 해결
 navbar 컴포넌트에  
```const changeNav = () => {
    if (window.scrollY >= 80) {
      setScrollNav(true);
    } else {
      setScrollNav(false);
    }
  };```
  다른 페이지 이동할 때 해당 스크롤이 변함에따라 state가 변하기전에 다른 페이지로 이동이 일어났음으로 일단 주석처리로 에러 해결 
  추후 useEffect 클린업 함수를 사용해서 해결예정 


### Estimated time
> Pick one
`2h`

### Labels
- Estimated time: E: 1h
- Group : client, server
- Sprint: Sprint__NUMBER__
- Urgency: High, Middle, Low
