### ISSUE TITLE
[서버] 뱃지에 관한 응답 라우팅 구현

### ISSUE THREAD

**Issue by loocia1910** [codestates/Mission-Eco#119]
### ISSUE
- Group:  server

### TODO
- [x] 뱃지 전체 리스트 응답
- [x] 마이 뱃지 리스트 응답
- [x] 뱃지 획득 응답

### Estimated time
`3h`
