### ISSUE TITLE
[서버] api 문서 수정 및 코드 작성

### ISSUE THREAD

**Issue by eden0514** [codestates/Mission-Eco#120]
### ISSUE
- Group: server
- Type: bug, feature, delete
- Detail: 서버부분 수정

### TODO
- [x] 챌린지 로그,마이 챌린지 로그 get 요청 api 문서 작성
- [x] challenge like 코드 수정
- [x] challenge log delete 코드 구현
- [x] model badge - challenge 1:1 연결로 수정

### Estimated time
> Pick one

`3h`

### Labels
- Estimated time: E: 3h
- Group : server
- Sprint: Sprint__NUMBER__
- Urgency: High, Middle, Low
