### ISSUE TITLE
[Front] 랜딩페이지 layout 구현

### ISSUE THREAD

**Issue by HYO00** [codestates/Mission-Eco#159]
### ISSUE
- Group: client
- Type: feature
- Detail: 드디어 메인 페이지를 만든다!! 잘 하자! 파이팅

### TODO
- [x] 와이어프레임 토대로 layout 구현 
- [x] 히어로 비디오 or 이미지 넣기
- [x] 랜딩화면 분류 후 꾸미기 

### Estimated time
> Pick one

`3h`

### Labels
- Estimated time: E: 1h
- Group : client, server
- Sprint: Sprint__NUMBER__
- Urgency: High, Middle, Low
