### ISSUE TITLE
[server] 관리자 페이지 관련 응답  작성 

### ISSUE THREAD

**Issue by eden0514** [codestates/Mission-Eco#161]
### ISSUE
- Group:  server,
- Type: feature
- Detail: 관리자 페이지 관련 응답  작성 

### TODO
- [x] 관리자 페이지 로그인 응답 작성
- [x] 관리자 페이지 챌린지 추가 응답 작성
- [x] 관리자 페이지 챌린지 로그 삭제 응답 작성

### Estimated time
> Pick one

`2h`

### Labels
- Estimated time: E: 2h
- Group : client, server
- Sprint: Sprint__NUMBER__
- Urgency: High, Middle, Low
