### ISSUE TITLE
[client] 관리자 페이지 구현

### ISSUE THREAD

**Issue by eden0514** [codestates/Mission-Eco#175]
### ISSUE
- Group: client
- Type: feature
- Detail: 관리자 페이지 구현

### TODO
- [x] 관리자 페이지 - challenge 추가하는 input 창 레이아웃 작업
- [x] 관리자 페이지 css 구현
- [x] challenge 페이지 네이션 구혀

### Estimated time
> Pick one

`3h`

### Labels
- Estimated time: E: 3h
- Group : client
- Sprint: Sprint__NUMBER__
- Urgency: High, Middle, Low
