### ISSUE TITLE
[server] DB dummy data 만들기

### ISSUE THREAD

**Issue by eden0514** [codestates/Mission-Eco#176]
### ISSUE
- Group: server
- Type:feature
- Detail: DB dummy data 만들기

### TODO
- [x] 챌린지 설명 적기
- [x] 유저, 챌린지, 챌린지 로그, 좋아요, 뱃지 더미데이터 생성
- [x] 챌린지 모델 부분에서 로그 가능한 챌린지 여부 확인하는 칼럼 추가

### Estimated time
> Pick one

`3h`

### Labels
- Estimated time: E: 3h
- Group : client, server
- Sprint: Sprint__NUMBER__
- Urgency: High, Middle, Low
