### ISSUE TITLE
[클라] 회원가입 유효성 검사 구현 및 CSS

### ISSUE THREAD

**Issue by loocia1910** [codestates/Mission-Eco#191]
### ISSUE
- Group: client

### TODO
- [x] 회원가입 레퍼런스 찾기
- [x] onBlur를 사용하여 현재 인풋창이 아닌 다른 곳 클릭시 서버에 요청이나 유효성 검사하기
- [x] 조건에 맞는 글씨 보이기 로직구현

### Estimated time
`3h`
