### ISSUE TITLE
[클라] 마이페이지 챌린지 로그 삭제 구현

### ISSUE THREAD

**Issue by loocia1910** [codestates/Mission-Eco#192]
### ISSUE
- Group: client

### TODO
- [x] 휴지통 아이콘 삽입
- [x] 서버로 현재 유저의 챌린지 로그 삭제 요청
- [x] 클라 리덕스에서 챌린지 로그의 현재 상태바꾸기

### Estimated time
`3h`
