### ISSUE TITLE
[클라] 현재 유저의 뱃지 획득 기능 구현 및 CSS

### ISSUE THREAD

**Issue by loocia1910** [codestates/Mission-Eco#193]
### ISSUE
- Group: client

### TODO
- [x] 뱃지 목록으로 보여주기 
- [ ] 각 챌린지 별로 처음으로 1개의 게시물을 작성하면 뱃지를 획득함
- [x] 유저의 챌린지 로그 리스트를 가져옴
- [x]  챌린지 아이디 별로 분류
- [x]  분류된 챌린지가 1개이상 일때
- [x] 해당 챌린지 뱃지 획득 (CSS)
      -> 획득한 경우(칼라), 획득하지 못한 경우(css 그레이 스케일)

### Estimated time
`3h`
