### ISSUE TITLE
11/10 수요일 작업현황 및 작업분배

### ISSUE THREAD

**Issue by HYO00** [codestates/Mission-Eco#213]
### ISSUE
- Group: client, server, sr
- Type: bug, feature, delete
- Detail: fix actions from client redux

### TODO
- [x] 새로고침시 로그인유지 (효영, 수경)
- [x] 모달 css 호버시 글자색-> 검은색 (양현)
- [x] 챌린지 카드 뒷면 글자조정 색깔? (양현)
- [x] 업로드 반응형, 미리보기 디자인 변경 (효영)
- [x] 로딩 컴포넌트 맞추기 (수경)
- [x] 더미데이터 (수경)
- [x] 무한스크롤 로딩 마지막에 멈추기(효영)
- [x] 회원탈퇴 모달 (정말 탈퇴하시겠습니까?) (양현)
- [x] Footer, 마이페이지 글자크기 (현진님)
- [x] 마이페이지 좋아요 라이크 리스트 모바일 크기 조절 (현진님)
- [x] 뱃지 테스트 (완료)
- [x] 로그인 로그아웃 alert 빼야됩니다. (양현님)
- [x] 티쳐블 머신 업데이트 (수경님)
- [x] 로그부분 각자 올리기 
- [x] 랜딩페이지 gif -> 꾸미기
- [x] 마이페이지 캐러셀? 주말에 시간남으면 하기 

수

오늘 하면서 코드도 정리를 해봅시다~~

오늘저녁 gif 만들기 

목 

랜딩페이지가 끝나야됩니다. 

- 5시 팀 리플렉션 줌 -> (발표준비)

금 (양현님 발표준비)
랜딩페이지가 끝나야됩니다. 

토 (양현님 주말 풀타임), (효영,현진,수경 )

일 

월 개인 기술발표 

화 팀 발표

### Estimated time
> Pick one

`0.5h`
`1h`
`1.5h`
`2h`
`2.5h`
`3h`

### Labels
- Estimated time: E: 1h
- Group : client, server
- Sprint: Sprint__NUMBER__
- Urgency: High, Middle, Low
