### ISSUE TITLE
금 마지막 남은작업

### ISSUE THREAD

**Issue by HYO00** [codestates/Mission-Eco#232]
### ISSUE
- Group: client, server, sr
- Type: bug, feature, delete
- Detail: fix actions from client redux

### TODO
- [x] 사이드바 오류 수정
- [x] 랜딩페이지 css 합치기 
- [x] 마이페이지 뱃지 불러오기 오류 수정
- [x] 뱃지 중복 
- [x] 랜딩페이지 전 로딩화면 제공 
- [x] 로딩컴포넌트 확인
- [x] 좋아요 숫자 오류 수정

### Estimated time
> Pick one

`0.5h`
`1h`
`1.5h`
`2h`
`2.5h`
`3h`

### Labels
- Estimated time: E: 1h
- Group : client, server
- Sprint: Sprint__NUMBER__
- Urgency: High, Middle, Low
