### ISSUE TITLE
정보 수정 확인 모달 - 함수 작성

### ISSUE THREAD

**Issue by cho-hyeonjin** [codestates/Mission-Eco#30]
### ISSUE
- Group: client
- Type: feature

### TODO

- [x] 마이페이지 수정 - 닉네임 변경 버튼 클릭시 {OO} 자리에 "닉네임을 변경"이 들어와야 함
- [x] 마이페이지 수정 - 비밀번호 변경 버튼 클릭시 {OO} 자리에 "비밀번호를 변경"이 들어와야 함
- [x] 마이페이지 수정 - 게시물 삭제
    - [x] 내 게시물 삭제 버튼 클릭시 {OO} 자리에 "삭제"가 들어와야 함
    - [x] 게시물 삭제 모달 -  "네" 버튼 클릭시 서버에 게시물 삭제 요청 보내는 함수 작성
- [x] 마이페이지 수정 - 회원 탈퇴
    - [x] 회원탈퇴 버튼 클릭시 {OO} 자리에 "회원 탈퇴"가 들어와야 함
    - [x] 회원탈퇴 모달 - "네" 버튼 클릭시 서버에 회원 탈퇴 요청 보내는 함수 작성
### Target time
`3h`
