### ISSUE TITLE
[서버] 회원가입 모듈 구현

### ISSUE THREAD

**Issue by loocia1910** [codestates/Mission-Eco#6]
### ISSUE
- Group: server

### TODO
- [ ] 이메일 중복 유효성 검사
- [ ] 닉네임 중복 유효성 검사
- [ ] 회원완료 데이터 생성
- [ ] bycript 암호화 구현
